version: "3.9"
services:
  frontend:
    image: tivdiss/frontend_ph:latest    # Changed from build to image
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
      
  backend:
    image: tivdiss/backend_ph:latest     # Changed from build to image
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=80332714
      - DB_NAME=productivity_hub
    depends_on:
      - db
    restart: unless-stopped
      
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 80332714
      MYSQL_DATABASE: productivity_hub
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
      
volumes:
  db_data: